name: Update this repo's README

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://northern-dev.net/feed.xml
          max: 10
          readme-section: feed
